from __future__ import annotations

import asyncio
from datetime import datetime
from pathlib import Path
from typing import Any

from sqlalchemy import select

from app.config import settings
from app.core.time import utcnow
from app.db.session import async_session
from app.models.background_job import BackgroundJob, BackgroundJobStatus, BackgroundJobType
from app.models.posting_session import PostingOperation
from app.models.user import User
from app.services.barcode_service import build_code39_png_b64, build_unique_barcode_value
from app.services import incident_service, reporting_service, request_workflow, update_service

try:
    from openpyxl import Workbook
except Exception:  # pragma: no cover
    Workbook = None

try:
    from weasyprint import HTML
except Exception:  # pragma: no cover
    HTML = None


def _artifact_dir() -> Path:
    p = Path(settings.artifacts_dir).expanduser().resolve()
    p.mkdir(parents=True, exist_ok=True)
    return p


def _job_file_path(job_id: str, extension: str) -> Path:
    return _artifact_dir() / f"{job_id}.{extension}"


def _iso_to_dt(value: str | None) -> datetime | None:
    if not value:
        return None
    try:
        return datetime.fromisoformat(value)
    except ValueError:
        return None


def _to_table_headers(rows: list[dict[str, Any]]) -> list[str]:
    if not rows:
        return []
    keys = list(rows[0].keys())
    return [str(k) for k in keys]


def _write_xlsx(
    *,
    target: Path,
    title: str,
    rows: list[dict[str, Any]],
    generated_by: str,
    filters: dict[str, Any],
) -> None:
    if Workbook is None:
        raise RuntimeError("openpyxl is not installed")
    wb = Workbook()
    ws = wb.active
    ws.title = "report"
    ws.append([title])
    ws.append([f"Generated by: {generated_by}"])
    ws.append([f"Generated at: {utcnow().isoformat()}"])
    ws.append([f"Filters: {filters}"])
    ws.append([])

    headers = _to_table_headers(rows)
    if headers:
        ws.append(headers)
        for row in rows:
            ws.append([row.get(h) for h in headers])
    else:
        ws.append(["No data"])
    wb.save(target)


def _write_pdf(
    *,
    target: Path,
    title: str,
    rows: list[dict[str, Any]],
    generated_by: str,
    filters: dict[str, Any],
) -> None:
    if HTML is None:
        raise RuntimeError("weasyprint is not available")
    generated_at = utcnow().isoformat()
    barcode_value = build_unique_barcode_value(
        ["PMM", "RPT", title, generated_by, generated_at, len(rows)]
    )
    barcode_b64 = build_code39_png_b64(barcode_value)
    headers = _to_table_headers(rows)
    header_html = "".join(f"<th>{h}</th>" for h in headers)
    body_html = ""
    for row in rows:
        body_html += "<tr>" + "".join(f"<td>{row.get(h, '')}</td>" for h in headers) + "</tr>"
    html = f"""
    <html>
    <head>
    <style>
    body {{ font-family: Arial, sans-serif; font-size: 12px; }}
    table {{ border-collapse: collapse; width: 100%; }}
    th, td {{ border: 1px solid #ddd; padding: 6px; text-align: left; }}
    th {{ background: #f3f3f3; }}
    .barcode-wrap {{ margin-top: 14px; }}
    .barcode-image {{ width: 260px; height: 62px; object-fit: fill; border: 1px solid #000; background: #fff; display: block; }}
    .barcode-value {{ font-size: 9px; margin-top: 2px; word-break: break-all; }}
    </style>
    </head>
    <body>
      <h2>{title}</h2>
      <p>Generated by: {generated_by}</p>
      <p>Generated at: {generated_at}</p>
      <p>Filters: {filters}</p>
      <table>
        <thead><tr>{header_html}</tr></thead>
        <tbody>{body_html}</tbody>
      </table>
      <div class="barcode-wrap">
        <img class="barcode-image" src="data:image/png;base64,{barcode_b64}" alt="Document barcode" />
        <div class="barcode-value">{barcode_value}</div>
      </div>
    </body>
    </html>
    """
    HTML(string=html).write_pdf(str(target))


async def enqueue_job(
    db,
    *,
    job_type: BackgroundJobType,
    params_json: dict[str, Any] | None,
    created_by: int | None,
) -> BackgroundJob:
    job = BackgroundJob(
        type=job_type,
        status=BackgroundJobStatus.QUEUED,
        params_json=params_json or {},
        created_by=created_by,
        created_at=utcnow(),
    )
    db.add(job)
    await db.flush()
    return job


def schedule_background_job(job_id: str) -> None:
    asyncio.create_task(run_background_job(job_id))


async def _resolve_user_display_name(user_id: int | None) -> str:
    if not user_id:
        return "SYSTEM"
    async with async_session() as db:
        row = (await db.execute(select(User).where(User.id == user_id))).scalars().first()
    if not row:
        return f"user#{user_id}"
    return row.full_name or row.login or f"user#{user_id}"


async def run_background_job(job_id: str) -> None:
    async with async_session() as db:
        job = (await db.execute(select(BackgroundJob).where(BackgroundJob.id == job_id))).scalars().first()
        if not job:
            return
        if job.status not in (BackgroundJobStatus.QUEUED, BackgroundJobStatus.FAILED):
            return
        job.status = BackgroundJobStatus.RUNNING
        job.started_at = utcnow()
        job.error_message = None
        await db.commit()

    try:
        result = await _run_job_payload(job_id)
    except Exception as exc:  # pragma: no cover - exercised in integration
        async with async_session() as db:
            job = (await db.execute(select(BackgroundJob).where(BackgroundJob.id == job_id))).scalars().first()
            if job:
                job.status = BackgroundJobStatus.FAILED
                job.finished_at = utcnow()
                job.error_message = str(exc)[:4000]
                await incident_service.create_incident(
                    db,
                    incident_type=incident_service.job_incident_type(job.type),
                    severity=incident_service.job_incident_severity(job.type),
                    message=f"{job.type.value if job.type else 'JOB'} failed: {exc}",
                    details_json={
                        "job_type": job.type.value if job.type else None,
                        "params_json": job.params_json,
                        "error_message": str(exc)[:4000],
                    },
                    job_id=job.id,
                    created_by=job.created_by,
                )
                await db.commit()
        return

    async with async_session() as db:
        job = (await db.execute(select(BackgroundJob).where(BackgroundJob.id == job_id))).scalars().first()
        if job:
            job.status = BackgroundJobStatus.SUCCESS
            job.finished_at = utcnow()
            job.result_json = result
            await db.commit()


async def _run_job_payload(job_id: str) -> dict[str, Any]:
    async with async_session() as db:
        job = (await db.execute(select(BackgroundJob).where(BackgroundJob.id == job_id))).scalars().first()
        if not job:
            raise RuntimeError("Job not found")
        params = dict(job.params_json or {})
        generated_by = await _resolve_user_display_name(job.created_by)

        if job.type == BackgroundJobType.RECONCILE:
            rows = await reporting_service.build_stock_reconcile_rows(db)
            out_path = _job_file_path(job.id, "xlsx")
            _write_xlsx(
                target=out_path,
                title="Stock Reconcile Report",
                rows=rows,
                generated_by=generated_by,
                filters=params.get("filters") or {},
            )
            return {
                "rows": rows,
                "row_count": len(rows),
                "file_path": str(out_path),
                "generated_by": generated_by,
            }

        if job.type == BackgroundJobType.MONTH_END_BATCH:
            request_ids = params.get("request_ids")
            actor_user_id = int(params.get("actor_user_id")) if params.get("actor_user_id") else None
            if actor_user_id is None:
                raise RuntimeError("MONTH_END_BATCH requires actor_user_id")
            target_ids = await request_workflow.month_end_pending_request_ids(
                db,
                request_ids=[int(x) for x in request_ids] if request_ids else None,
            )
            processed = []
            failed = []
            for rid in target_ids:
                try:
                    posting_session, state = await request_workflow.start_posting_session(
                        db,
                        request_id=rid,
                        operation=PostingOperation.MONTH_END_CONFIRM,
                        idempotency_key=f"job:{job.id}:request:{rid}",
                        started_by_user_id=actor_user_id,
                    )
                    if state == "SUCCESS":
                        session_result = posting_session.result_json or posting_session.result_ref or {}
                        processed.append(
                            {
                                "request_id": rid,
                                "result": session_result.get("result", "SUCCESS"),
                                "issue_doc_no": session_result.get("issue_doc_no"),
                                "already_done": True,
                            }
                        )
                        continue
                    if state == "IN_PROGRESS":
                        failed.append({"request_id": rid, "error": "posting already in progress"})
                        continue

                    result = await request_workflow.confirm_request_posting(
                        db,
                        request_id=rid,
                        actor_user_id=actor_user_id,
                        force_admin_month_end=True,
                        audit_action="MONTH_END_CONFIRM",
                    )
                    await request_workflow.mark_posting_session_success(
                        db,
                        posting_session=posting_session,
                        result_ref=request_workflow.confirm_result_ref(result),
                    )
                    await db.commit()
                    processed.append(
                        {
                            "request_id": rid,
                            "result": result.result,
                            "issue_doc_no": result.issue.issue_doc_no if result.issue else None,
                        }
                    )
                except Exception as exc:
                    await db.rollback()
                    try:
                        posting_session, state = await request_workflow.start_posting_session(
                            db,
                            request_id=rid,
                            operation=PostingOperation.MONTH_END_CONFIRM,
                            idempotency_key=f"job:{job.id}:request:{rid}",
                            started_by_user_id=actor_user_id,
                        )
                        if state != "IN_PROGRESS":
                            await request_workflow.mark_posting_session_failed(
                                db,
                                posting_session=posting_session,
                                error_code="MONTH_END_CONFIRM_FAILED",
                                error_message=str(exc),
                            )
                            await request_workflow.create_admin_alert(
                                db,
                                alert_type="MONTH_END_CONFIRM_FAILED",
                                severity="HIGH",
                                message=f"Month-end confirm failed for request {rid}: {exc}",
                                request_id=rid,
                                posting_session_id=posting_session.id,
                            )
                            await db.commit()
                    except Exception:
                        await db.rollback()
                    failed.append({"request_id": rid, "error": str(exc)})
            return {"processed": processed, "failed": failed}

        if job.type in (
            BackgroundJobType.REQUESTS_EXPORT,
            BackgroundJobType.DEBTS_EXPORT,
            BackgroundJobType.VEHICLE_REPORT_EXPORT,
        ):
            export_format = str(params.get("format") or "XLSX").upper()
            filters = params.get("filters") or {}
            rows: list[dict[str, Any]]
            title: str
            if job.type == BackgroundJobType.REQUESTS_EXPORT:
                rows = await reporting_service.build_requests_rows(
                    db,
                    department_id=filters.get("department_id"),
                    status=filters.get("status"),
                )
                title = "Requests Export"
            elif job.type == BackgroundJobType.DEBTS_EXPORT:
                rows = await reporting_service.build_debts_rows(
                    db,
                    department_id=filters.get("department_id"),
                    only_open=bool(filters.get("only_open")),
                )
                title = "Debts Export"
            else:
                rows = await reporting_service.build_vehicle_consumption_rows(
                    db,
                    date_from=_iso_to_dt(filters.get("date_from")),
                    date_to=_iso_to_dt(filters.get("date_to")),
                    department_id=filters.get("department_id"),
                    vehicle_id=filters.get("vehicle_id"),
                    fuel_type=filters.get("fuel_type"),
                    route_contains=filters.get("route_contains"),
                )
                title = "Vehicle Consumption Report"

            if export_format == "PDF":
                out_path = _job_file_path(job.id, "pdf")
                _write_pdf(
                    target=out_path,
                    title=title,
                    rows=rows,
                    generated_by=generated_by,
                    filters=filters,
                )
            else:
                out_path = _job_file_path(job.id, "xlsx")
                _write_xlsx(
                    target=out_path,
                    title=title,
                    rows=rows,
                    generated_by=generated_by,
                    filters=filters,
                )

            return {
                "row_count": len(rows),
                "file_path": str(out_path),
                "format": export_format,
                "generated_by": generated_by,
                "filters": filters,
            }

        if job.type == BackgroundJobType.SYSTEM_UPDATE:
            if not settings.updater_mode:
                raise RuntimeError("SYSTEM_UPDATE jobs can run only in updater service")
            return await update_service.run_system_update_job(
                db,
                job_id=job.id,
                mode=str(params.get("mode") or "UPDATE"),
                target_version=params.get("target_version"),
                with_backup=bool(params.get("with_backup")) if "with_backup" in params else None,
                started_by=int(params.get("started_by") or job.created_by or 0) or None,
                update_log_id=int(params.get("update_log_id")) if params.get("update_log_id") is not None else None,
                to_version=params.get("to_version"),
            )

        raise RuntimeError(f"Unsupported job type: {job.type}")
